//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TabScore.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A.
        /// </summary>
        public static string A {
            get {
                return ResourceManager.GetString("A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All PASS.
        /// </summary>
        public static string AllPass {
            get {
                return ResourceManager.GetString("AllPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arbitral score.
        /// </summary>
        public static string ArbitralScore {
            get {
                return ResourceManager.GetString("ArbitralScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Board.
        /// </summary>
        public static string Board {
            get {
                return ResourceManager.GetString("Board", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boards.
        /// </summary>
        public static string Boards {
            get {
                return ResourceManager.GetString("Boards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to by.
        /// </summary>
        public static string by {
            get {
                return ResourceManager.GetString("by", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By.
        /// </summary>
        public static string ByOnTraveller {
            get {
                return ResourceManager.GetString("ByOnTraveller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm result.
        /// </summary>
        public static string ConfirmResult {
            get {
                return ResourceManager.GetString("ConfirmResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contract.
        /// </summary>
        public static string Contract {
            get {
                return ResourceManager.GetString("Contract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dealer.
        /// </summary>
        public static string Dealer {
            get {
                return ResourceManager.GetString("Dealer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E.
        /// </summary>
        public static string E {
            get {
                return ResourceManager.GetString("E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to East.
        /// </summary>
        public static string East {
            get {
                return ResourceManager.GetString("East", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End screen.
        /// </summary>
        public static string EndScreen {
            get {
                return ResourceManager.GetString("EndScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter.
        /// </summary>
        public static string Enter {
            get {
                return ResourceManager.GetString("Enter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter contract.
        /// </summary>
        public static string EnterContract {
            get {
                return ResourceManager.GetString("EnterContract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter/edit player IDs.
        /// </summary>
        public static string EnterEditPlayerIDs {
            get {
                return ResourceManager.GetString("EnterEditPlayerIDs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter ID for.
        /// </summary>
        public static string EnterID {
            get {
                return ResourceManager.GetString("EnterID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter lead.
        /// </summary>
        public static string EnterLead {
            get {
                return ResourceManager.GetString("EnterLead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter player IDs.
        /// </summary>
        public static string EnterPlayerIDs {
            get {
                return ResourceManager.GetString("EnterPlayerIDs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter tricks taken.
        /// </summary>
        public static string EnterTricksTaken {
            get {
                return ResourceManager.GetString("EnterTricksTaken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occurred whilst connecting to the scoring database.
        /// </summary>
        public static string ErrorDBConnection {
            get {
                return ResourceManager.GetString("ErrorDBConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a result (or Skip = Not played) for every board.
        /// </summary>
        public static string ErrorEnterResult {
            get {
                return ResourceManager.GetString("ErrorEnterResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Scoring Database selected; please wait until the Tournament Director tells you to start.
        /// </summary>
        public static string ErrorNoDBSelected {
            get {
                return ResourceManager.GetString("ErrorNoDBSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a player ID, or select &apos;Unknown&apos;.
        /// </summary>
        public static string ErrorNoID {
            get {
                return ResourceManager.GetString("ErrorNoID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File TabScoreDB.txt doesn&apos;t exist.  Please re-start TabScoreStarter.exe.
        /// </summary>
        public static string ErrorNoTabScoreDBtxt {
            get {
                return ResourceManager.GetString("ErrorNoTabScoreDBtxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select an ID or &apos;Unknown&apos; for all players.
        /// </summary>
        public static string ErrorNotAllIDs {
            get {
                return ResourceManager.GetString("ErrorNotAllIDs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permanent database connection error.  Please check format and access permissions for Scoring Database file, and re-start TabScoreStarter.exe.
        /// </summary>
        public static string ErrorPermanentDB {
            get {
                return ResourceManager.GetString("ErrorPermanentDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please click OK to try to re-establish the connection.  If successful, please re-register this tablet to your [section/]table number[/direction].
        /// </summary>
        public static string ErrorReestablishConnection {
            get {
                return ResourceManager.GetString("ErrorReestablishConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error screen.
        /// </summary>
        public static string ErrorScreen {
            get {
                return ResourceManager.GetString("ErrorScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table.
        /// </summary>
        public static string ErrorTableNotReady1 {
            get {
                return ResourceManager.GetString("ErrorTableNotReady1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is not yet ready.  Please wait.
        /// </summary>
        public static string ErrorTableNotReady2 {
            get {
                return ResourceManager.GetString("ErrorTableNotReady2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table.
        /// </summary>
        public static string ErrorTableRegistered1 {
            get {
                return ResourceManager.GetString("ErrorTableRegistered1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to and direction.
        /// </summary>
        public static string ErrorTableRegistered2 {
            get {
                return ResourceManager.GetString("ErrorTableRegistered2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is already registered.  Do not press Register unless you intend to re-register a tablet device at your current location.
        /// </summary>
        public static string ErrorTableRegistered3 {
            get {
                return ResourceManager.GetString("ErrorTableRegistered3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait until all the player IDs for this table have been entered.
        /// </summary>
        public static string ErrorWaitAllIDs {
            get {
                return ResourceManager.GetString("ErrorWaitAllIDs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait until there is a result entered for this board.
        /// </summary>
        public static string ErrorWaitResult {
            get {
                return ResourceManager.GetString("ErrorWaitResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait until there are results entered for every board.
        /// </summary>
        public static string ErrorWaitResults {
            get {
                return ResourceManager.GetString("ErrorWaitResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For Swiss events, wait until the TD tells you and then press OK to get the new movement.
        /// </summary>
        public static string ForSwiss {
            get {
                return ResourceManager.GetString("ForSwiss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If the event is finished, you can turn off the tablet device.
        /// </summary>
        public static string IfFinished {
            get {
                return ResourceManager.GetString("IfFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to J.
        /// </summary>
        public static string J {
            get {
                return ResourceManager.GetString("J", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to K.
        /// </summary>
        public static string K {
            get {
                return ResourceManager.GetString("K", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lead.
        /// </summary>
        public static string Lead {
            get {
                return ResourceManager.GetString("Lead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lead does not match hand record.
        /// </summary>
        public static string LeadNoMatch {
            get {
                return ResourceManager.GetString("LeadNoMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move for Round.
        /// </summary>
        public static string MoveForRound {
            get {
                return ResourceManager.GetString("MoveForRound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move to sit-out.
        /// </summary>
        public static string MoveToSitOut {
            get {
                return ResourceManager.GetString("MoveToSitOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move to Table.
        /// </summary>
        public static string MoveToTable {
            get {
                return ResourceManager.GetString("MoveToTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N.
        /// </summary>
        public static string N {
            get {
                return ResourceManager.GetString("N", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter all the player IDs before pressing OK.
        /// </summary>
        public static string NeedAllIDs {
            get {
                return ResourceManager.GetString("NeedAllIDs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to North.
        /// </summary>
        public static string North {
            get {
                return ResourceManager.GetString("North", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not played.
        /// </summary>
        public static string NotPlayed {
            get {
                return ResourceManager.GetString("NotPlayed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This tablet device is not being used for scoring during this round.  Once a board has been scored, you can view it using the buttons below.
        /// </summary>
        public static string NotScoring {
            get {
                return ResourceManager.GetString("NotScoring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NT.
        /// </summary>
        public static string NT {
            get {
                return ResourceManager.GetString("NT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pair.
        /// </summary>
        public static string Pair {
            get {
                return ResourceManager.GetString("Pair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pair No..
        /// </summary>
        public static string PairNumber {
            get {
                return ResourceManager.GetString("PairNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PASS.
        /// </summary>
        public static string Pass {
            get {
                return ResourceManager.GetString("Pass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pass to relay table.
        /// </summary>
        public static string PassToRelayTable {
            get {
                return ResourceManager.GetString("PassToRelayTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pass to Table.
        /// </summary>
        public static string PassToTable {
            get {
                return ResourceManager.GetString("PassToTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Percentage.
        /// </summary>
        public static string Percentage {
            get {
                return ResourceManager.GetString("Percentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %age.
        /// </summary>
        public static string PercentageShort {
            get {
                return ResourceManager.GetString("PercentageShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player.
        /// </summary>
        public static string Player {
            get {
                return ResourceManager.GetString("Player", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player no..
        /// </summary>
        public static string PlayerNumber {
            get {
                return ResourceManager.GetString("PlayerNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Q.
        /// </summary>
        public static string Q {
            get {
                return ResourceManager.GetString("Q", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rank.
        /// </summary>
        public static string Rank {
            get {
                return ResourceManager.GetString("Rank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ranking list.
        /// </summary>
        public static string RankingList {
            get {
                return ResourceManager.GetString("RankingList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Round.
        /// </summary>
        public static string Round {
            get {
                return ResourceManager.GetString("Round", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S.
        /// </summary>
        public static string S {
            get {
                return ResourceManager.GetString("S", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Score.
        /// </summary>
        public static string Score {
            get {
                return ResourceManager.GetString("Score", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Score entry complete.
        /// </summary>
        public static string ScoreEntryComplete {
            get {
                return ResourceManager.GetString("ScoreEntryComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Section.
        /// </summary>
        public static string Section {
            get {
                return ResourceManager.GetString("Section", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select direction.
        /// </summary>
        public static string SelectDirection {
            get {
                return ResourceManager.GetString("SelectDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select section.
        /// </summary>
        public static string SelectSection {
            get {
                return ResourceManager.GetString("SelectSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select table number.
        /// </summary>
        public static string SelectTableNumber {
            get {
                return ResourceManager.GetString("SelectTableNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show boards.
        /// </summary>
        public static string ShowBoards {
            get {
                return ResourceManager.GetString("ShowBoards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show final ranking list.
        /// </summary>
        public static string ShowFinalRankingList {
            get {
                return ResourceManager.GetString("ShowFinalRankingList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show hand record.
        /// </summary>
        public static string ShowHandRecord {
            get {
                return ResourceManager.GetString("ShowHandRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show move.
        /// </summary>
        public static string ShowMove {
            get {
                return ResourceManager.GetString("ShowMove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show player IDs.
        /// </summary>
        public static string ShowPlayerIDs {
            get {
                return ResourceManager.GetString("ShowPlayerIDs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show ranking list.
        /// </summary>
        public static string ShowRankingList {
            get {
                return ResourceManager.GetString("ShowRankingList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show round info.
        /// </summary>
        public static string ShowRoundInfo {
            get {
                return ResourceManager.GetString("ShowRoundInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show traveller.
        /// </summary>
        public static string ShowTraveller {
            get {
                return ResourceManager.GetString("ShowTraveller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sitout.
        /// </summary>
        public static string Sitout {
            get {
                return ResourceManager.GetString("Sitout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sitting out.
        /// </summary>
        public static string SittingOut {
            get {
                return ResourceManager.GetString("SittingOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sitting out away from the numbered tables.
        /// </summary>
        public static string SittingOutNoTable {
            get {
                return ResourceManager.GetString("SittingOutNoTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip.
        /// </summary>
        public static string Skip {
            get {
                return ResourceManager.GetString("Skip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to South.
        /// </summary>
        public static string South {
            get {
                return ResourceManager.GetString("South", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stay at Table.
        /// </summary>
        public static string StayAtTable {
            get {
                return ResourceManager.GetString("StayAtTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table.
        /// </summary>
        public static string Table {
            get {
                return ResourceManager.GetString("Table", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to T.
        /// </summary>
        public static string TenShorthand {
            get {
                return ResourceManager.GetString("TenShorthand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to.
        /// </summary>
        public static string To {
            get {
                return ResourceManager.GetString("To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Traveller.
        /// </summary>
        public static string Traveller {
            get {
                return ResourceManager.GetString("Traveller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tricks.
        /// </summary>
        public static string Tricks {
            get {
                return ResourceManager.GetString("Tricks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        public static string Unknown {
            get {
                return ResourceManager.GetString("Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        public static string View {
            get {
                return ResourceManager.GetString("View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to W.
        /// </summary>
        public static string W {
            get {
                return ResourceManager.GetString("W", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait until the TD calls the move, and then move to the next table before pressing OK.
        /// </summary>
        public static string WaitNextTable {
            get {
                return ResourceManager.GetString("WaitNextTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait until the Tournament Director tells you to start, and then press OK.
        /// </summary>
        public static string WaitTD {
            get {
                return ResourceManager.GetString("WaitTD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait until the TD calls the move and this table is ready to start before pressing OK.
        /// </summary>
        public static string WaitThisTable {
            get {
                return ResourceManager.GetString("WaitThisTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        public static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to West.
        /// </summary>
        public static string West {
            get {
                return ResourceManager.GetString("West", resourceCulture);
            }
        }
    }
}
