//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TabScoreStarter {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TabScoreStarter.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 40%-40%.
        /// </summary>
        public static string _40__40_ {
            get {
                return ResourceManager.GetString("40%-40%", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 40%-50%.
        /// </summary>
        public static string _40__50_ {
            get {
                return ResourceManager.GetString("40%-50%", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 40%-60%.
        /// </summary>
        public static string _40__60_ {
            get {
                return ResourceManager.GetString("40%-60%", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 50%-40%.
        /// </summary>
        public static string _50__40_ {
            get {
                return ResourceManager.GetString("50%-40%", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 50%-50%.
        /// </summary>
        public static string _50__50_ {
            get {
                return ResourceManager.GetString("50%-50%", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 50%-60%.
        /// </summary>
        public static string _50__60_ {
            get {
                return ResourceManager.GetString("50%-60%", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 60%-40%.
        /// </summary>
        public static string _60__40_ {
            get {
                return ResourceManager.GetString("60%-40%", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 60%-50%.
        /// </summary>
        public static string _60__50_ {
            get {
                return ResourceManager.GetString("60%-50%", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 60%-60%.
        /// </summary>
        public static string _60__60_ {
            get {
                return ResourceManager.GetString("60%-60%", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analysing....
        /// </summary>
        public static string Analysing {
            get {
                return ResourceManager.GetString("Analysing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analysis Complete.
        /// </summary>
        public static string AnalysisComplete {
            get {
                return ResourceManager.GetString("AnalysisComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arbitral score.
        /// </summary>
        public static string Arbitral_score {
            get {
                return ResourceManager.GetString("Arbitral score", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Board.
        /// </summary>
        public static string Board {
            get {
                return ResourceManager.GetString("Board", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C10.
        /// </summary>
        public static string C10 {
            get {
                return ResourceManager.GetString("C10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C2.
        /// </summary>
        public static string C2 {
            get {
                return ResourceManager.GetString("C2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C3.
        /// </summary>
        public static string C3 {
            get {
                return ResourceManager.GetString("C3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C4.
        /// </summary>
        public static string C4 {
            get {
                return ResourceManager.GetString("C4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C5.
        /// </summary>
        public static string C5 {
            get {
                return ResourceManager.GetString("C5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C6.
        /// </summary>
        public static string C6 {
            get {
                return ResourceManager.GetString("C6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C7.
        /// </summary>
        public static string C7 {
            get {
                return ResourceManager.GetString("C7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C8.
        /// </summary>
        public static string C8 {
            get {
                return ResourceManager.GetString("C8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C9.
        /// </summary>
        public static string C9 {
            get {
                return ResourceManager.GetString("C9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CA.
        /// </summary>
        public static string CA {
            get {
                return ResourceManager.GetString("CA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change hand record file....
        /// </summary>
        public static string ChangeHandRecordFile {
            get {
                return ResourceManager.GetString("ChangeHandRecordFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CJ.
        /// </summary>
        public static string CJ {
            get {
                return ResourceManager.GetString("CJ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CK.
        /// </summary>
        public static string CK {
            get {
                return ResourceManager.GetString("CK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CQ.
        /// </summary>
        public static string CQ {
            get {
                return ResourceManager.GetString("CQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D10.
        /// </summary>
        public static string D10 {
            get {
                return ResourceManager.GetString("D10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D2.
        /// </summary>
        public static string D2 {
            get {
                return ResourceManager.GetString("D2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D3.
        /// </summary>
        public static string D3 {
            get {
                return ResourceManager.GetString("D3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D4.
        /// </summary>
        public static string D4 {
            get {
                return ResourceManager.GetString("D4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D5.
        /// </summary>
        public static string D5 {
            get {
                return ResourceManager.GetString("D5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D6.
        /// </summary>
        public static string D6 {
            get {
                return ResourceManager.GetString("D6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D7.
        /// </summary>
        public static string D7 {
            get {
                return ResourceManager.GetString("D7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D8.
        /// </summary>
        public static string D8 {
            get {
                return ResourceManager.GetString("D8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D9.
        /// </summary>
        public static string D9 {
            get {
                return ResourceManager.GetString("D9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DA.
        /// </summary>
        public static string DA {
            get {
                return ResourceManager.GetString("DA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database passed in parameter string does not exist.
        /// </summary>
        public static string DatabaseNotExist {
            get {
                return ResourceManager.GetString("DatabaseNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DJ.
        /// </summary>
        public static string DJ {
            get {
                return ResourceManager.GetString("DJ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DK.
        /// </summary>
        public static string DK {
            get {
                return ResourceManager.GetString("DK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DQ.
        /// </summary>
        public static string DQ {
            get {
                return ResourceManager.GetString("DQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E.
        /// </summary>
        public static string E {
            get {
                return ResourceManager.GetString("E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter valid contract details.
        /// </summary>
        public static string EnterValidContract {
            get {
                return ResourceManager.GetString("EnterValidContract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid result.
        /// </summary>
        public static string EnterValidResult {
            get {
                return ResourceManager.GetString("EnterValidResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File contains no hand records.
        /// </summary>
        public static string FileNoHandRecords {
            get {
                return ResourceManager.GetString("FileNoHandRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to H10.
        /// </summary>
        public static string H10 {
            get {
                return ResourceManager.GetString("H10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to H2.
        /// </summary>
        public static string H2 {
            get {
                return ResourceManager.GetString("H2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to H3.
        /// </summary>
        public static string H3 {
            get {
                return ResourceManager.GetString("H3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to H4.
        /// </summary>
        public static string H4 {
            get {
                return ResourceManager.GetString("H4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to H5.
        /// </summary>
        public static string H5 {
            get {
                return ResourceManager.GetString("H5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to H6.
        /// </summary>
        public static string H6 {
            get {
                return ResourceManager.GetString("H6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to H7.
        /// </summary>
        public static string H7 {
            get {
                return ResourceManager.GetString("H7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to H8.
        /// </summary>
        public static string H8 {
            get {
                return ResourceManager.GetString("H8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to H9.
        /// </summary>
        public static string H9 {
            get {
                return ResourceManager.GetString("H9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HA.
        /// </summary>
        public static string HA {
            get {
                return ResourceManager.GetString("HA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HJ.
        /// </summary>
        public static string HJ {
            get {
                return ResourceManager.GetString("HJ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HK.
        /// </summary>
        public static string HK {
            get {
                return ResourceManager.GetString("HK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HQ.
        /// </summary>
        public static string HQ {
            get {
                return ResourceManager.GetString("HQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Included in Scoring Database.
        /// </summary>
        public static string IncludedInDatabase {
            get {
                return ResourceManager.GetString("IncludedInDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N.
        /// </summary>
        public static string N {
            get {
                return ResourceManager.GetString("N", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not played.
        /// </summary>
        public static string Not_played {
            get {
                return ResourceManager.GetString("Not played", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pair EW.
        /// </summary>
        public static string PairEW {
            get {
                return ResourceManager.GetString("PairEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pair NS.
        /// </summary>
        public static string PairNS {
            get {
                return ResourceManager.GetString("PairNS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PASS.
        /// </summary>
        public static string PASS {
            get {
                return ResourceManager.GetString("PASS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Round.
        /// </summary>
        public static string Round {
            get {
                return ResourceManager.GetString("Round", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S.
        /// </summary>
        public static string S {
            get {
                return ResourceManager.GetString("S", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S10.
        /// </summary>
        public static string S10 {
            get {
                return ResourceManager.GetString("S10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S2.
        /// </summary>
        public static string S2 {
            get {
                return ResourceManager.GetString("S2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S3.
        /// </summary>
        public static string S3 {
            get {
                return ResourceManager.GetString("S3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S4.
        /// </summary>
        public static string S4 {
            get {
                return ResourceManager.GetString("S4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S5.
        /// </summary>
        public static string S5 {
            get {
                return ResourceManager.GetString("S5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S6.
        /// </summary>
        public static string S6 {
            get {
                return ResourceManager.GetString("S6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S7.
        /// </summary>
        public static string S7 {
            get {
                return ResourceManager.GetString("S7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S8.
        /// </summary>
        public static string S8 {
            get {
                return ResourceManager.GetString("S8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S9.
        /// </summary>
        public static string S9 {
            get {
                return ResourceManager.GetString("S9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SA.
        /// </summary>
        public static string SA {
            get {
                return ResourceManager.GetString("SA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Section.
        /// </summary>
        public static string Section {
            get {
                return ResourceManager.GetString("Section", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session Running.
        /// </summary>
        public static string SessionRunning {
            get {
                return ResourceManager.GetString("SessionRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SJ.
        /// </summary>
        public static string SJ {
            get {
                return ResourceManager.GetString("SJ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SK.
        /// </summary>
        public static string SK {
            get {
                return ResourceManager.GetString("SK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQ.
        /// </summary>
        public static string SQ {
            get {
                return ResourceManager.GetString("SQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C.
        /// </summary>
        public static string SuitC {
            get {
                return ResourceManager.GetString("SuitC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D.
        /// </summary>
        public static string SuitD {
            get {
                return ResourceManager.GetString("SuitD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to H.
        /// </summary>
        public static string SuitH {
            get {
                return ResourceManager.GetString("SuitH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NT.
        /// </summary>
        public static string SuitNT {
            get {
                return ResourceManager.GetString("SuitNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S.
        /// </summary>
        public static string SuitS {
            get {
                return ResourceManager.GetString("SuitS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table.
        /// </summary>
        public static string Table {
            get {
                return ResourceManager.GetString("Table", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to W.
        /// </summary>
        public static string W {
            get {
                return ResourceManager.GetString("W", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong direction.
        /// </summary>
        public static string Wrong_direction {
            get {
                return ResourceManager.GetString("Wrong direction", resourceCulture);
            }
        }
    }
}
